apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - system/namespace.yaml
  - triage/namespace.yaml
  - triage/networkpolicy.yaml
  - triage/rbac.yaml
  - triage/configmap-prompt.yaml
  - triage/cronjob.yaml
